"""DDL PostgreSQL, precondicoes e isolamento da revision 130500."""

import hashlib
import importlib.util
from io import StringIO
from pathlib import Path
from types import ModuleType
from unittest.mock import MagicMock

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations

from app.db.base import Base

ROOT = Path(__file__).resolve().parents[1]
MIGRATION = ROOT / "migrations/versions/202609130500_bike_tour_operations.py"
PREVIOUS = {
    "202609130100_bike_tour_foundation.py": (
        "17ea083821e3e97ce8af0e30e9ef23b1f4274e6ecbf2f6850bf358cc2e6eb7e0"
    ),
    "202609130200_bike_tour_core.py": (
        "15766127590e950663a32db1d49b50fee7de8df1e404adb2f721d20bc4957cfd"
    ),
    "202609130300_bike_tour_allocations.py": (
        "3949abe1a058e3f63605b5f9de11da3b6851318e6e4a70819f38196d30f96f19"
    ),
    "202609130400_bike_tour_integrity.py": (
        "51bb855d8ffb4d1c2cf119bdf364193dbe1b6489fc51216bdb93dc11c4fc9119"
    ),
}
TABLES = (
    "equipe_bike_tour",
    "logistica_bike_tour",
    "ponto_controle_bike_tour",
    "passagem_bike_tour",
    "ocorrencia_bike_tour",
    "avaliacao_bike_tour",
)


@pytest.fixture
def migration() -> ModuleType:
    spec = importlib.util.spec_from_file_location("bike_tour_operations", MIGRATION)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_revision_e_preservacao_das_quatro_anteriores(migration: ModuleType) -> None:
    assert migration.revision == "202609130500"
    assert migration.down_revision == "202609130400"
    assert migration.TABLES == TABLES
    for name, digest in PREVIOUS.items():
        # Normaliza somente EOL, permitido pela politica de checkout do repositorio.
        source = (MIGRATION.parent / name).read_bytes().replace(b"\r\n", b"\n")
        assert hashlib.sha256(source).hexdigest() == digest


def test_ddl_completo_e_downgrade_restrito(
    migration: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    buffer = StringIO()
    context = MigrationContext.configure(
        dialect_name="postgresql",
        opts={
            "as_sql": True,
            "output_buffer": buffer,
            "target_metadata": Base.metadata,
        },
    )
    monkeypatch.setattr(migration, "_validate_prerequisites", lambda: None)
    monkeypatch.setattr(migration, "_validate_created_tables", lambda: None)
    with Operations.context(context):
        migration.upgrade()
    sql = buffer.getvalue()
    assert sql.count("CREATE TABLE public.") == 6
    assert sql.count("CREATE TRIGGER ") == 12
    for table in TABLES:
        assert f"CONSTRAINT pk_{table} PRIMARY KEY (id_{table})" in sql
        assert f"CONSTRAINT ck_{table}_versao_positiva CHECK (versao >= 1)" in sql
        assert f"COMMENT ON TABLE public.{table}" in sql
        assert f"COMMENT ON COLUMN public.{table}.created_by" in sql
        assert f"CREATE TRIGGER trg_{table}_updated_at" in sql
        assert f"CREATE TRIGGER trg_{table}_auditoria" in sql
    assert "FOREIGN KEY(id_localidade) REFERENCES public.localidade (id_localidade)" in sql
    assert "WHERE papel = 'LIDER' AND deleted_at IS NULL" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "TIMESTAMP WITH TIME ZONE" in sql
    assert "ck_equipe_bike_tour_ck_" not in sql
    buffer.seek(0)
    buffer.truncate()
    with Operations.context(context):
        migration.downgrade()
    assert buffer.getvalue().strip().split(";\n\n") == [
        f"DROP TABLE public.{table}" + (";" if table == TABLES[0] else "")
        for table in reversed(TABLES)
    ]


@pytest.mark.parametrize("missing", range(6))
def test_prerequisito_invalido_aborta_antes_do_ddl(
    migration: ModuleType,
    monkeypatch: pytest.MonkeyPatch,
    missing: int,
) -> None:
    operations = MagicMock()
    operations.get_bind.return_value.execute.return_value.scalar_one.side_effect = [
        True
    ] * missing + [False]
    monkeypatch.setattr(migration, "op", operations)
    with pytest.raises(RuntimeError, match="Prerequisito Bike Tour"):
        migration.upgrade()
    operations.create_table.assert_not_called()


def test_pos_validacao_rejeita_trigger_ausente(
    migration: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    operations = MagicMock()
    operations.get_bind.return_value.execute.return_value.scalar_one.return_value = 1
    monkeypatch.setattr(migration, "op", operations)
    with pytest.raises(RuntimeError, match="Validacao da auditoria"):
        migration._validate_created_tables()
