/* ============================================================================
   WMA TRAVEL ERP
   F1-FIN.11 — TRIBUTOS, EMPRESTIMOS E IMOBILIZADO

   PostgreSQL : 18.x
   Banco      : wma_travel
   Etapa      : F1-FIN.11
   Modo       : COMPLEMENTACAO CONTROLADA / CERTIFICACAO

   REGRA ARQUITETURAL
   ------------------
   financeiro = autoridade do dominio financeiro
   public     = corporativo / transversal

   OBJETIVO
   --------
   Consolidar em um unico script:
     1. Pre-validacao.
     2. Inventario dos objetos existentes relacionados a:
        - Tributos
        - Emprestimos / financiamentos
        - Ativo imobilizado
     3. Complementacao minima quando necessario.
     4. Integracao com financeiro.lancamento.
     5. Testes funcionais controlados.
     6. Limpeza dos dados artificiais.
     7. Certificacao final da F1-FIN.11.

   SEGURANCA
   ---------
   - Transacao unica.
   - ON_ERROR_STOP.
   - Sem DROP.
   - Sem CASCADE.
   - Testes artificiais removidos antes do COMMIT.
   - COMMIT somente apos certificacao final.
   ============================================================================ */

\set ON_ERROR_STOP on
\pset pager off
\pset null '(NULL)'
\timing on

BEGIN;

SET client_encoding = 'UTF8';
SET lock_timeout = '10s';
SET statement_timeout = '0';

\echo ''
\echo '============================================================'
\echo ' WMA TRAVEL ERP'
\echo ' F1-FIN.11 - TRIBUTOS, EMPRESTIMOS E IMOBILIZADO'
\echo '============================================================'

/* ============================================================================
   1. AMBIENTE
   ============================================================================ */

\echo ''
\echo '=== 1 - AMBIENTE ==='

SELECT
    current_database() AS banco,
    current_user AS usuario,
    current_setting('server_version') AS postgresql,
    current_setting('server_encoding') AS server_encoding,
    current_setting('client_encoding') AS client_encoding,
    CURRENT_TIMESTAMP AS executado_em;

/* ============================================================================
   2. PRE-VALIDACAO
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 2 - PRE-VALIDACAO'
\echo '============================================================'

DO $$
DECLARE
    v_count bigint;
BEGIN
    IF current_database() <> 'wma_travel' THEN
        RAISE EXCEPTION
            'F1-FIN.11 abortada: banco atual %, esperado wma_travel.',
            current_database();
    END IF;

    IF to_regclass('financeiro.lancamento') IS NULL THEN
        RAISE EXCEPTION
            'F1-FIN.11 abortada: financeiro.lancamento ausente.';
    END IF;

    IF to_regclass('public.empresa') IS NULL THEN
        RAISE EXCEPTION
            'F1-FIN.11 abortada: public.empresa ausente.';
    END IF;

    SELECT count(*)
    INTO v_count
    FROM public.empresa;

    IF v_count = 0 THEN
        RAISE EXCEPTION
            'F1-FIN.11 abortada: public.empresa sem registros.';
    END IF;
END
$$;

\echo 'PRE-VALIDACAO: PASS'

/* ============================================================================
   3. INVENTARIO DE OBJETOS EXISTENTES
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 3 - INVENTARIO DE OBJETOS'
\echo '============================================================'

SELECT
    n.nspname AS schema_name,
    c.relname AS object_name,
    CASE c.relkind
        WHEN 'r' THEN 'TABLE'
        WHEN 'p' THEN 'PARTITIONED TABLE'
        WHEN 'v' THEN 'VIEW'
        WHEN 'm' THEN 'MATERIALIZED VIEW'
        ELSE c.relkind::text
    END AS object_type
FROM pg_class c
JOIN pg_namespace n
  ON n.oid = c.relnamespace
WHERE n.nspname NOT LIKE 'pg_%'
  AND n.nspname <> 'information_schema'
  AND c.relkind IN ('r','p','v','m')
  AND c.relname ~* '(tribut|imposto|emprest|financ|imobil|depreci)'
ORDER BY n.nspname, c.relname;

/* ============================================================================
   4. TRIBUTOS
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 4 - TRIBUTOS'
\echo '============================================================'

CREATE TABLE IF NOT EXISTS financeiro.tributo (
    id_tributo bigint GENERATED BY DEFAULT AS IDENTITY,
    id_empresa integer NOT NULL,
    codigo character varying(30) NOT NULL,
    descricao character varying(120) NOT NULL,
    competencia date NOT NULL,
    vencimento date NOT NULL,
    valor_principal numeric(15,2) NOT NULL,
    multa numeric(15,2) NOT NULL DEFAULT 0,
    juros numeric(15,2) NOT NULL DEFAULT 0,
    desconto numeric(15,2) NOT NULL DEFAULT 0,
    valor_total numeric(15,2)
        GENERATED ALWAYS AS (
            valor_principal + multa + juros - desconto
        ) STORED,
    pago boolean NOT NULL DEFAULT FALSE,
    data_pagamento date,
    id_lancamento bigint,
    ativo boolean NOT NULL DEFAULT TRUE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    created_by integer,
    updated_by integer,
    deleted_by integer,
    versao integer NOT NULL DEFAULT 1,

    CONSTRAINT pk_tributo
        PRIMARY KEY (id_tributo),

    CONSTRAINT chk_tributo_valor_principal
        CHECK (valor_principal > 0),

    CONSTRAINT chk_tributo_multa
        CHECK (multa >= 0),

    CONSTRAINT chk_tributo_juros
        CHECK (juros >= 0),

    CONSTRAINT chk_tributo_desconto
        CHECK (desconto >= 0),

    CONSTRAINT chk_tributo_total
        CHECK (valor_total >= 0),

    CONSTRAINT fk_tributo_empresa
        FOREIGN KEY (id_empresa)
        REFERENCES public.empresa(id_empresa)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_tributo_lancamento
        FOREIGN KEY (id_lancamento)
        REFERENCES financeiro.lancamento(id_lancamento)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_tributo_created_by
        FOREIGN KEY (created_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_tributo_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_tributo_deleted_by
        FOREIGN KEY (deleted_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

/* ============================================================================
   5. EMPRESTIMOS
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 5 - EMPRESTIMOS'
\echo '============================================================'

CREATE TABLE IF NOT EXISTS financeiro.emprestimo (
    id_emprestimo bigint GENERATED BY DEFAULT AS IDENTITY,
    id_empresa integer NOT NULL,
    descricao character varying(150) NOT NULL,
    instituicao character varying(120),
    data_contratacao date NOT NULL,
    valor_principal numeric(15,2) NOT NULL,
    taxa_juros numeric(10,6) NOT NULL DEFAULT 0,
    quantidade_parcelas integer NOT NULL,
    saldo_devedor numeric(15,2) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'ATIVO',
    id_lancamento bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    created_by integer,
    updated_by integer,
    deleted_by integer,
    versao integer NOT NULL DEFAULT 1,

    CONSTRAINT pk_emprestimo
        PRIMARY KEY (id_emprestimo),

    CONSTRAINT chk_emprestimo_valor
        CHECK (valor_principal > 0),

    CONSTRAINT chk_emprestimo_taxa
        CHECK (taxa_juros >= 0),

    CONSTRAINT chk_emprestimo_parcelas
        CHECK (quantidade_parcelas > 0),

    CONSTRAINT chk_emprestimo_saldo
        CHECK (saldo_devedor >= 0),

    CONSTRAINT chk_emprestimo_status
        CHECK (status IN ('ATIVO','QUITADO','CANCELADO')),

    CONSTRAINT fk_emprestimo_empresa
        FOREIGN KEY (id_empresa)
        REFERENCES public.empresa(id_empresa)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_emprestimo_lancamento
        FOREIGN KEY (id_lancamento)
        REFERENCES financeiro.lancamento(id_lancamento)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_emprestimo_created_by
        FOREIGN KEY (created_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_emprestimo_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_emprestimo_deleted_by
        FOREIGN KEY (deleted_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

/* ============================================================================
   6. PARCELAS DE EMPRESTIMO
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 6 - PARCELAS DE EMPRESTIMO'
\echo '============================================================'

CREATE TABLE IF NOT EXISTS financeiro.emprestimo_parcela (
    id_emprestimo_parcela bigint GENERATED BY DEFAULT AS IDENTITY,
    id_emprestimo bigint NOT NULL,
    numero_parcela integer NOT NULL,
    vencimento date NOT NULL,
    valor_principal numeric(15,2) NOT NULL,
    juros numeric(15,2) NOT NULL DEFAULT 0,
    multa numeric(15,2) NOT NULL DEFAULT 0,
    desconto numeric(15,2) NOT NULL DEFAULT 0,
    valor_total numeric(15,2)
        GENERATED ALWAYS AS (
            valor_principal + juros + multa - desconto
        ) STORED,
    valor_pago numeric(15,2) NOT NULL DEFAULT 0,
    saldo numeric(15,2)
        GENERATED ALWAYS AS (
            valor_principal + juros + multa - desconto - valor_pago
        ) STORED,
    status character varying(20) NOT NULL DEFAULT 'ABERTA',
    id_lancamento bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_emprestimo_parcela
        PRIMARY KEY (id_emprestimo_parcela),

    CONSTRAINT uk_emprestimo_parcela
        UNIQUE (id_emprestimo, numero_parcela),

    CONSTRAINT chk_emprestimo_parcela_numero
        CHECK (numero_parcela > 0),

    CONSTRAINT chk_emprestimo_parcela_principal
        CHECK (valor_principal > 0),

    CONSTRAINT chk_emprestimo_parcela_juros
        CHECK (juros >= 0),

    CONSTRAINT chk_emprestimo_parcela_multa
        CHECK (multa >= 0),

    CONSTRAINT chk_emprestimo_parcela_desconto
        CHECK (desconto >= 0),

    CONSTRAINT chk_emprestimo_parcela_pago
        CHECK (valor_pago >= 0),

    CONSTRAINT chk_emprestimo_parcela_saldo
        CHECK (saldo >= 0),

    CONSTRAINT chk_emprestimo_parcela_status
        CHECK (status IN ('ABERTA','PARCIAL','PAGA','VENCIDA','CANCELADA')),

    CONSTRAINT fk_emprestimo_parcela_emprestimo
        FOREIGN KEY (id_emprestimo)
        REFERENCES financeiro.emprestimo(id_emprestimo)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_emprestimo_parcela_lancamento
        FOREIGN KEY (id_lancamento)
        REFERENCES financeiro.lancamento(id_lancamento)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

/* ============================================================================
   7. ATIVO IMOBILIZADO
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 7 - ATIVO IMOBILIZADO'
\echo '============================================================'

CREATE TABLE IF NOT EXISTS financeiro.ativo_imobilizado (
    id_ativo bigint GENERATED BY DEFAULT AS IDENTITY,
    id_empresa integer NOT NULL,
    codigo character varying(40) NOT NULL,
    descricao character varying(150) NOT NULL,
    data_aquisicao date NOT NULL,
    valor_aquisicao numeric(15,2) NOT NULL,
    valor_residual numeric(15,2) NOT NULL DEFAULT 0,
    vida_util_meses integer NOT NULL,
    taxa_depreciacao numeric(10,6),
    depreciacao_acumulada numeric(15,2) NOT NULL DEFAULT 0,
    status character varying(20) NOT NULL DEFAULT 'ATIVO',
    id_lancamento bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    created_by integer,
    updated_by integer,
    deleted_by integer,
    versao integer NOT NULL DEFAULT 1,

    CONSTRAINT pk_ativo_imobilizado
        PRIMARY KEY (id_ativo),

    CONSTRAINT uk_ativo_imobilizado_codigo
        UNIQUE (codigo),

    CONSTRAINT chk_ativo_imobilizado_valor
        CHECK (valor_aquisicao > 0),

    CONSTRAINT chk_ativo_imobilizado_residual
        CHECK (valor_residual >= 0),

    CONSTRAINT chk_ativo_imobilizado_vida
        CHECK (vida_util_meses > 0),

    CONSTRAINT chk_ativo_imobilizado_depreciacao
        CHECK (depreciacao_acumulada >= 0),

    CONSTRAINT chk_ativo_imobilizado_status
        CHECK (status IN ('ATIVO','BAIXADO','VENDIDO','INATIVO')),

    CONSTRAINT fk_ativo_imobilizado_empresa
        FOREIGN KEY (id_empresa)
        REFERENCES public.empresa(id_empresa)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_ativo_imobilizado_lancamento
        FOREIGN KEY (id_lancamento)
        REFERENCES financeiro.lancamento(id_lancamento)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_ativo_imobilizado_created_by
        FOREIGN KEY (created_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_ativo_imobilizado_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_ativo_imobilizado_deleted_by
        FOREIGN KEY (deleted_by)
        REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

/* ============================================================================
   8. DEPRECIACAO
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 8 - DEPRECIACAO'
\echo '============================================================'

CREATE TABLE IF NOT EXISTS financeiro.depreciacao_ativo (
    id_depreciacao bigint GENERATED BY DEFAULT AS IDENTITY,
    id_ativo bigint NOT NULL,
    competencia date NOT NULL,
    valor numeric(15,2) NOT NULL,
    id_lancamento bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_depreciacao_ativo
        PRIMARY KEY (id_depreciacao),

    CONSTRAINT uk_depreciacao_ativo_competencia
        UNIQUE (id_ativo, competencia),

    CONSTRAINT chk_depreciacao_ativo_valor
        CHECK (valor > 0),

    CONSTRAINT fk_depreciacao_ativo_ativo
        FOREIGN KEY (id_ativo)
        REFERENCES financeiro.ativo_imobilizado(id_ativo)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_depreciacao_ativo_lancamento
        FOREIGN KEY (id_lancamento)
        REFERENCES financeiro.lancamento(id_lancamento)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

/* ============================================================================
   9. INDICES
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 9 - INDICES'
\echo '============================================================'

CREATE INDEX IF NOT EXISTS idx_tributo_empresa_competencia
    ON financeiro.tributo(id_empresa, competencia);

CREATE INDEX IF NOT EXISTS idx_tributo_vencimento
    ON financeiro.tributo(vencimento);

CREATE INDEX IF NOT EXISTS idx_emprestimo_empresa
    ON financeiro.emprestimo(id_empresa);

CREATE INDEX IF NOT EXISTS idx_emprestimo_parcela_vencimento
    ON financeiro.emprestimo_parcela(vencimento);

CREATE INDEX IF NOT EXISTS idx_ativo_imobilizado_empresa
    ON financeiro.ativo_imobilizado(id_empresa);

CREATE INDEX IF NOT EXISTS idx_depreciacao_ativo_competencia
    ON financeiro.depreciacao_ativo(id_ativo, competencia);

/* ============================================================================
   10. DOCUMENTACAO
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 10 - DOCUMENTACAO'
\echo '============================================================'

COMMENT ON TABLE financeiro.tributo IS
    'Controle de obrigacoes tributarias do modulo financeiro.';

COMMENT ON TABLE financeiro.emprestimo IS
    'Contratos de emprestimos e financiamentos da empresa.';

COMMENT ON TABLE financeiro.emprestimo_parcela IS
    'Parcelas financeiras vinculadas a contratos de emprestimos.';

COMMENT ON TABLE financeiro.ativo_imobilizado IS
    'Controle financeiro dos ativos imobilizados da empresa.';

COMMENT ON TABLE financeiro.depreciacao_ativo IS
    'Lancamentos periodicos de depreciacao dos ativos imobilizados.';

/* ============================================================================
   11. REAUDITORIA DE OBJETOS
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 11 - REAUDITORIA DE OBJETOS'
\echo '============================================================'

WITH esperado(objeto) AS (
    VALUES
        ('tributo'),
        ('emprestimo'),
        ('emprestimo_parcela'),
        ('ativo_imobilizado'),
        ('depreciacao_ativo')
)
SELECT
    objeto,
    CASE
        WHEN to_regclass('financeiro.' || objeto) IS NOT NULL
            THEN 'OK'
        ELSE 'AUSENTE'
    END AS status
FROM esperado
ORDER BY objeto;

/* ============================================================================
   12. REAUDITORIA DE CONSTRAINTS
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 12 - REAUDITORIA DE CONSTRAINTS'
\echo '============================================================'

SELECT
    c.relname AS table_name,
    COUNT(*) AS constraints,
    COUNT(*) FILTER (WHERE NOT con.convalidated) AS nao_validadas
FROM pg_constraint con
JOIN pg_class c
  ON c.oid = con.conrelid
JOIN pg_namespace n
  ON n.oid = c.relnamespace
WHERE n.nspname = 'financeiro'
  AND c.relname IN (
      'tributo',
      'emprestimo',
      'emprestimo_parcela',
      'ativo_imobilizado',
      'depreciacao_ativo'
  )
GROUP BY c.relname
ORDER BY c.relname;

/* ============================================================================
   13. TESTE FUNCIONAL CONTROLADO
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 13 - TESTE FUNCIONAL'
\echo '============================================================'

CREATE TEMP TABLE f1_fin_11_test_ctx (
    id_tributo bigint,
    id_emprestimo bigint,
    id_emprestimo_parcela bigint,
    id_ativo bigint,
    id_depreciacao bigint
);

DO $$
DECLARE
    v_empresa integer;
    v_tributo bigint;
    v_emp bigint;
    v_parc bigint;
    v_ativo bigint;
    v_dep bigint;
BEGIN
    SELECT id_empresa
    INTO v_empresa
    FROM public.empresa
    ORDER BY id_empresa
    LIMIT 1;

    INSERT INTO financeiro.tributo (
        id_empresa,
        codigo,
        descricao,
        competencia,
        vencimento,
        valor_principal,
        multa,
        juros,
        desconto,
        pago
    )
    VALUES (
        v_empresa,
        'F1FIN11-TRIB',
        'Teste funcional tributo',
        date_trunc('month', CURRENT_DATE)::date,
        CURRENT_DATE + 10,
        1000.00,
        10.00,
        5.00,
        15.00,
        FALSE
    )
    RETURNING id_tributo INTO v_tributo;

    INSERT INTO financeiro.emprestimo (
        id_empresa,
        descricao,
        instituicao,
        data_contratacao,
        valor_principal,
        taxa_juros,
        quantidade_parcelas,
        saldo_devedor,
        status
    )
    VALUES (
        v_empresa,
        'Teste F1-FIN.11',
        'BANCO TESTE',
        CURRENT_DATE,
        12000.00,
        1.5,
        12,
        12000.00,
        'ATIVO'
    )
    RETURNING id_emprestimo INTO v_emp;

    INSERT INTO financeiro.emprestimo_parcela (
        id_emprestimo,
        numero_parcela,
        vencimento,
        valor_principal,
        juros,
        multa,
        desconto,
        valor_pago,
        status
    )
    VALUES (
        v_emp,
        1,
        CURRENT_DATE + 30,
        1000.00,
        15.00,
        0.00,
        0.00,
        0.00,
        'ABERTA'
    )
    RETURNING id_emprestimo_parcela INTO v_parc;

    INSERT INTO financeiro.ativo_imobilizado (
        id_empresa,
        codigo,
        descricao,
        data_aquisicao,
        valor_aquisicao,
        valor_residual,
        vida_util_meses,
        taxa_depreciacao,
        depreciacao_acumulada,
        status
    )
    VALUES (
        v_empresa,
        'F1FIN11-ATIVO',
        'Notebook teste',
        CURRENT_DATE,
        6000.00,
        600.00,
        60,
        20.000000,
        0.00,
        'ATIVO'
    )
    RETURNING id_ativo INTO v_ativo;

    INSERT INTO financeiro.depreciacao_ativo (
        id_ativo,
        competencia,
        valor
    )
    VALUES (
        v_ativo,
        date_trunc('month', CURRENT_DATE)::date,
        90.00
    )
    RETURNING id_depreciacao INTO v_dep;

    INSERT INTO f1_fin_11_test_ctx
    VALUES (
        v_tributo,
        v_emp,
        v_parc,
        v_ativo,
        v_dep
    );
END
$$;

/* ============================================================================
   14. VALIDACAO FUNCIONAL
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 14 - VALIDACAO FUNCIONAL'
\echo '============================================================'

SELECT
    t.codigo,
    t.valor_principal,
    t.multa,
    t.juros,
    t.desconto,
    t.valor_total
FROM financeiro.tributo t
WHERE t.id_tributo IN (
    SELECT id_tributo FROM f1_fin_11_test_ctx
);

SELECT
    ep.valor_principal,
    ep.juros,
    ep.valor_total,
    ep.valor_pago,
    ep.saldo
FROM financeiro.emprestimo_parcela ep
WHERE ep.id_emprestimo_parcela IN (
    SELECT id_emprestimo_parcela FROM f1_fin_11_test_ctx
);

DO $$
DECLARE
    v_count bigint;
BEGIN
    SELECT count(*)
    INTO v_count
    FROM financeiro.tributo
    WHERE id_tributo IN (
        SELECT id_tributo FROM f1_fin_11_test_ctx
    )
      AND valor_total = 1000.00;

    IF v_count <> 1 THEN
        RAISE EXCEPTION
            'F1-FIN.11 falhou: calculo do tributo nao aprovado.';
    END IF;

    SELECT count(*)
    INTO v_count
    FROM financeiro.emprestimo_parcela
    WHERE id_emprestimo_parcela IN (
        SELECT id_emprestimo_parcela FROM f1_fin_11_test_ctx
    )
      AND valor_total = 1015.00
      AND saldo = 1015.00;

    IF v_count <> 1 THEN
        RAISE EXCEPTION
            'F1-FIN.11 falhou: calculo da parcela de emprestimo nao aprovado.';
    END IF;

    SELECT count(*)
    INTO v_count
    FROM financeiro.ativo_imobilizado
    WHERE id_ativo IN (
        SELECT id_ativo FROM f1_fin_11_test_ctx
    )
      AND valor_aquisicao = 6000.00
      AND vida_util_meses = 60;

    IF v_count <> 1 THEN
        RAISE EXCEPTION
            'F1-FIN.11 falhou: teste de ativo imobilizado nao aprovado.';
    END IF;

    SELECT count(*)
    INTO v_count
    FROM financeiro.depreciacao_ativo
    WHERE id_depreciacao IN (
        SELECT id_depreciacao FROM f1_fin_11_test_ctx
    )
      AND valor = 90.00;

    IF v_count <> 1 THEN
        RAISE EXCEPTION
            'F1-FIN.11 falhou: teste de depreciacao nao aprovado.';
    END IF;
END
$$;

/* ============================================================================
   15. LIMPEZA DOS DADOS DE TESTE
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 15 - LIMPEZA DOS DADOS DE TESTE'
\echo '============================================================'

DELETE FROM financeiro.depreciacao_ativo
WHERE id_depreciacao IN (
    SELECT id_depreciacao FROM f1_fin_11_test_ctx
);

DELETE FROM financeiro.ativo_imobilizado
WHERE id_ativo IN (
    SELECT id_ativo FROM f1_fin_11_test_ctx
);

DELETE FROM financeiro.emprestimo_parcela
WHERE id_emprestimo_parcela IN (
    SELECT id_emprestimo_parcela FROM f1_fin_11_test_ctx
);

DELETE FROM financeiro.emprestimo
WHERE id_emprestimo IN (
    SELECT id_emprestimo FROM f1_fin_11_test_ctx
);

DELETE FROM financeiro.tributo
WHERE id_tributo IN (
    SELECT id_tributo FROM f1_fin_11_test_ctx
);

/* ============================================================================
   16. CERTIFICACAO FINAL
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' 16 - CERTIFICACAO FINAL F1-FIN.11'
\echo '============================================================'

WITH integridade AS (
    SELECT
        (
            SELECT COUNT(*)
            FROM pg_constraint con
            JOIN pg_class c
              ON c.oid = con.conrelid
            JOIN pg_namespace n
              ON n.oid = c.relnamespace
            WHERE n.nspname = 'financeiro'
              AND c.relname IN (
                  'tributo',
                  'emprestimo',
                  'emprestimo_parcela',
                  'ativo_imobilizado',
                  'depreciacao_ativo'
              )
              AND NOT con.convalidated
        ) AS constraints_nao_validadas,

        (
            SELECT COUNT(*) FROM financeiro.tributo
            WHERE codigo = 'F1FIN11-TRIB'
        ) AS teste_tributo,

        (
            SELECT COUNT(*) FROM financeiro.emprestimo
            WHERE descricao = 'Teste F1-FIN.11'
        ) AS teste_emprestimo,

        (
            SELECT COUNT(*) FROM financeiro.ativo_imobilizado
            WHERE codigo = 'F1FIN11-ATIVO'
        ) AS teste_ativo
)
SELECT
    CASE WHEN to_regclass('financeiro.tributo') IS NOT NULL THEN 1 ELSE 0 END AS tributo,
    CASE WHEN to_regclass('financeiro.emprestimo') IS NOT NULL THEN 1 ELSE 0 END AS emprestimo,
    CASE WHEN to_regclass('financeiro.emprestimo_parcela') IS NOT NULL THEN 1 ELSE 0 END AS emprestimo_parcela,
    CASE WHEN to_regclass('financeiro.ativo_imobilizado') IS NOT NULL THEN 1 ELSE 0 END AS ativo_imobilizado,
    CASE WHEN to_regclass('financeiro.depreciacao_ativo') IS NOT NULL THEN 1 ELSE 0 END AS depreciacao_ativo,
    i.constraints_nao_validadas,
    i.teste_tributo,
    i.teste_emprestimo,
    i.teste_ativo,
    CASE
        WHEN to_regclass('financeiro.tributo') IS NOT NULL
         AND to_regclass('financeiro.emprestimo') IS NOT NULL
         AND to_regclass('financeiro.emprestimo_parcela') IS NOT NULL
         AND to_regclass('financeiro.ativo_imobilizado') IS NOT NULL
         AND to_regclass('financeiro.depreciacao_ativo') IS NOT NULL
         AND i.constraints_nao_validadas = 0
         AND i.teste_tributo = 0
         AND i.teste_emprestimo = 0
         AND i.teste_ativo = 0
        THEN 'F1_FIN_11_APROVADA'
        ELSE 'F1_FIN_11_PENDENTE'
    END AS status
FROM integridade i;

/* ============================================================================
   17. VALIDACAO BLOQUEANTE FINAL
   ============================================================================ */

DO $$
DECLARE
    v_invalid bigint;
BEGIN
    SELECT COUNT(*)
    INTO v_invalid
    FROM pg_constraint con
    JOIN pg_class c
      ON c.oid = con.conrelid
    JOIN pg_namespace n
      ON n.oid = c.relnamespace
    WHERE n.nspname = 'financeiro'
      AND c.relname IN (
          'tributo',
          'emprestimo',
          'emprestimo_parcela',
          'ativo_imobilizado',
          'depreciacao_ativo'
      )
      AND NOT con.convalidated;

    IF v_invalid <> 0 THEN
        RAISE EXCEPTION
            'F1-FIN.11 abortada: % constraints nao validadas.',
            v_invalid;
    END IF;

    IF EXISTS (
        SELECT 1 FROM financeiro.tributo WHERE codigo = 'F1FIN11-TRIB'
    )
    OR EXISTS (
        SELECT 1 FROM financeiro.emprestimo WHERE descricao = 'Teste F1-FIN.11'
    )
    OR EXISTS (
        SELECT 1 FROM financeiro.ativo_imobilizado WHERE codigo = 'F1FIN11-ATIVO'
    ) THEN
        RAISE EXCEPTION
            'F1-FIN.11 abortada: dados de teste permaneceram.';
    END IF;
END
$$;

/* ============================================================================
   COMMIT
   ============================================================================ */

\echo ''
\echo '============================================================'
\echo ' F1-FIN.11 CONCLUIDA'
\echo '============================================================'
\echo ' TRIBUTOS ........................ IMPLEMENTADOS/VALIDADOS'
\echo ' EMPRESTIMOS ..................... IMPLEMENTADOS/VALIDADOS'
\echo ' PARCELAS DE EMPRESTIMO .......... IMPLEMENTADAS/VALIDADAS'
\echo ' ATIVO IMOBILIZADO ............... IMPLEMENTADO/VALIDADO'
\echo ' DEPRECIACAO ..................... IMPLEMENTADA/VALIDADA'
\echo ' TESTES FUNCIONAIS ............... APROVADOS'
\echo ' DOCUMENTACAO .................... APLICADA'
\echo ' PROXIMA ETAPA ................... F1-FIN.12'
\echo '============================================================'

COMMIT;

\echo ''
\echo '============================================================'
\echo ' COMMIT CONCLUIDO'
\echo ' F1-FIN.11 FINALIZADA'
\echo ' PROXIMA ETAPA: F1-FIN.12 - AUDITORIA DE INTEGRIDADE FINANCEIRA'
\echo '============================================================'
