"""Registro central dos models gerenciados pelo Alembic."""

from app.modules.comercial.models import (
    CondicaoComercial,
    Contrato,
    FunilVenda,
    InteracaoLead,
    ItemProposta,
    ItemVenda,
    Lead,
    Operadora,
    Oportunidade,
    OrigemLead,
    Proposta,
    Venda,
)
from app.modules.corporativo.models import (
    Cliente,
    ConfiguracaoEmpresa,
    Documento,
    Empresa,
    Fornecedor,
    Localidade,
    ParametroSistema,
    Pessoa,
    TipoDocumento,
)
from app.modules.seguranca.models import (
    EventoSeguranca,
    PerfilAcesso,
    PerfilPermissao,
    Permissao,
    RecuperacaoCredencial,
    SessaoUsuario,
    Usuario,
    UsuarioPerfil,
)

__all__ = [
    "Cliente",
    "CondicaoComercial",
    "ConfiguracaoEmpresa",
    "Contrato",
    "Documento",
    "Empresa",
    "EventoSeguranca",
    "Fornecedor",
    "FunilVenda",
    "InteracaoLead",
    "ItemProposta",
    "ItemVenda",
    "Lead",
    "Localidade",
    "Operadora",
    "Oportunidade",
    "OrigemLead",
    "ParametroSistema",
    "PerfilAcesso",
    "PerfilPermissao",
    "Permissao",
    "Proposta",
    "RecuperacaoCredencial",
    "Pessoa",
    "SessaoUsuario",
    "TipoDocumento",
    "Usuario",
    "UsuarioPerfil",
    "Venda",
]
