-- Hardening 2.6: requer migration 202609050100 e baseline certificada.
-- Executar pela migration Alembic 202609080100, em uma única transação.
-- Pré-validação: constraints validadas recusam dados incompatíveis; nada é corrigido silenciosamente.
-- Pós-validação: constraints e triggers devem existir e estar habilitados.
ALTER TABLE public.reserva ADD CONSTRAINT ck_reserva_quantidade_passageiros
    CHECK (quantidade_passageiros IS NOT NULL AND quantidade_passageiros > 0);
ALTER TABLE public.reserva ADD CONSTRAINT ck_reserva_valor_total CHECK (valor_total >= 0);
ALTER TABLE public.alocacao_vaga ADD CONSTRAINT uq_alocacao_vaga_id_reserva UNIQUE (id_reserva);
CREATE INDEX idx_alocacao_vaga_id_saida_status_expira_em
    ON public.alocacao_vaga (id_saida, status, expira_em);
CREATE TABLE public.reserva_operacao (
    id_reserva_operacao integer GENERATED BY DEFAULT AS IDENTITY,
    id_reserva integer NOT NULL,
    id_usuario integer,
    operacao varchar(20) NOT NULL,
    chave_idempotencia varchar(100) NOT NULL,
    resultado json NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp,
    deleted_at timestamp,
    created_by varchar(100),
    updated_by varchar(100),
    deleted_by varchar(100),
    versao integer NOT NULL DEFAULT 1,
    CONSTRAINT pk_reserva_operacao PRIMARY KEY (id_reserva_operacao),
    CONSTRAINT fk_reserva_operacao_reserva FOREIGN KEY (id_reserva) REFERENCES public.reserva(id_reserva),
    CONSTRAINT fk_reserva_operacao_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario),
    CONSTRAINT uq_reserva_operacao_intencao UNIQUE NULLS NOT DISTINCT
        (id_reserva, operacao, id_usuario, chave_idempotencia),
    CONSTRAINT ck_reserva_operacao_operacao CHECK (operacao IN ('CONFIRMAR', 'CANCELAR'))
);
COMMENT ON TABLE public.reserva_operacao IS 'Resultado original das acoes idempotentes de reserva.';
COMMENT ON COLUMN public.reserva_operacao.id_reserva_operacao IS 'Identificador da operacao persistida.';
COMMENT ON COLUMN public.reserva_operacao.id_reserva IS 'Reserva proprietaria da intencao.';
COMMENT ON COLUMN public.reserva_operacao.id_usuario IS 'Ator autenticado; nulo somente para chamada interna.';
COMMENT ON COLUMN public.reserva_operacao.operacao IS 'CONFIRMAR ou CANCELAR; parte do escopo da chave.';
COMMENT ON COLUMN public.reserva_operacao.chave_idempotencia IS 'Chave opaca sem dados pessoais; escopo reserva e operacao.';
COMMENT ON COLUMN public.reserva_operacao.resultado IS 'Snapshot imutavel da resposta original, sem dados de passageiro.';
COMMENT ON COLUMN public.reserva_operacao.created_at IS 'Instante UTC de criacao.';
COMMENT ON COLUMN public.reserva_operacao.updated_at IS 'Instante UTC de atualizacao.';
COMMENT ON COLUMN public.reserva_operacao.deleted_at IS 'Instante UTC de exclusao logica.';
COMMENT ON COLUMN public.reserva_operacao.created_by IS 'Ator da criacao.';
COMMENT ON COLUMN public.reserva_operacao.updated_by IS 'Ator da atualizacao.';
COMMENT ON COLUMN public.reserva_operacao.deleted_by IS 'Ator da exclusao logica.';
COMMENT ON COLUMN public.reserva_operacao.versao IS 'Versao do registro.';
CREATE TRIGGER trg_reserva_operacao_updated_at BEFORE UPDATE ON public.reserva_operacao
    FOR EACH ROW EXECUTE FUNCTION public.fn_atualiza_updated_at();
CREATE TRIGGER trg_reserva_operacao_auditoria AFTER INSERT OR UPDATE OR DELETE ON public.reserva_operacao
    FOR EACH ROW EXECUTE FUNCTION public.fn_log_auditoria();

-- Coerência entre tabelas é avaliada no commit, depois de todas as escritas da unidade atômica.
CREATE FUNCTION public.fn_validar_reserva_alocacao() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE alvo integer;
BEGIN
    alvo := NEW.id_reserva;
    IF EXISTS (
        SELECT 1 FROM public.reserva r JOIN public.alocacao_vaga a USING (id_reserva)
        WHERE r.id_reserva = alvo AND (
            r.id_saida IS DISTINCT FROM a.id_saida OR r.quantidade_passageiros <> a.quantidade OR
            r.status IS NULL OR
            NOT ((r.status = 'PENDENTE' AND a.status IN ('BLOQUEADA','RESERVADA','EXPIRADA')) OR
                 (r.status IN ('CONFIRMADA','CONCLUIDA','NO_SHOW') AND a.status = 'RESERVADA') OR
                 (r.status = 'CANCELADA' AND a.status IN ('LIBERADA','EXPIRADA')))
        )
    ) THEN
        RAISE EXCEPTION 'reserva e alocacao incoerentes' USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END $$;
COMMENT ON FUNCTION public.fn_validar_reserva_alocacao()
    IS 'Valida coerencia de reserva e alocacao ao final da transacao.';
CREATE CONSTRAINT TRIGGER trg_reserva_coerencia AFTER INSERT OR UPDATE ON public.reserva
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.fn_validar_reserva_alocacao();
CREATE CONSTRAINT TRIGGER trg_alocacao_vaga_coerencia AFTER INSERT OR UPDATE ON public.alocacao_vaga
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.fn_validar_reserva_alocacao();
-- Verifica também o estado preexistente, sem alterar dados.
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM public.reserva r JOIN public.alocacao_vaga a USING (id_reserva)
        WHERE r.id_saida IS DISTINCT FROM a.id_saida OR r.quantidade_passageiros <> a.quantidade OR
            r.status IS NULL OR
            NOT ((r.status = 'PENDENTE' AND a.status IN ('BLOQUEADA','RESERVADA','EXPIRADA')) OR
                 (r.status IN ('CONFIRMADA','CONCLUIDA','NO_SHOW') AND a.status = 'RESERVADA') OR
                 (r.status = 'CANCELADA' AND a.status IN ('LIBERADA','EXPIRADA')))
    ) THEN RAISE EXCEPTION 'dados preexistentes incoerentes'; END IF;
END $$;
